### ISSUE TITLE
cypher to query change (need for documentation)

### ISSUE THREAD

**Issue by arisAlexis** [thingdom/node-neo4j#166] opened 2015-08-11 09:47 UTC
I was trying to run the example with db.cypher and I had to read coffeescript code to realise in v2 there was a change and cypher method doesn't exist.

**Comment by aseemk** [comment] 2015-08-11 13:18
I'm not sure what issue you're encountering — a `cypher` method very much exists in v2. =)

Using v2, this example should work:

https://github.com/thingdom/node-neo4j/tree/v2#usage

Does it not? What error do you see?

**Comment by MaarekElets** [comment] 2015-08-11 15:08
This looks like more of a coffeescript documentation issue. The cypher command is not listed in the documentation that I can find. Query is there but there's no reference to cypher under GraphDatabase.

**Comment by aseemk** [comment] 2015-08-11 15:10
Ohhh, you're referring to the coffeedoc.info documentation. That's indeed for v1, which did not have a `cypher` method. For v2, please refer to this for now:

https://github.com/thingdom/node-neo4j/blob/v2/API_v2.md

v2 documentation is still in progress. That's the last remaining thing before v2 gets merged to master.

Sorry for the confusion!

**Closed by aseemk** 2015-08-11 15:10 UTC
Labels: question

**Comment by MaarekElets** [comment] 2015-08-11 15:31
That makes sense. I think the confusion was mostly caused by https://github.com/thingdom/node-neo4j/blob/v2/README.md still referencing the V1 API docs. It's something I'm sure will be cleaned up right before the push to V2. Thanks for pointing our the API_V2.MD that's exactly what I was wanting to have open in my browser as I code!

**Comment by aseemk** [comment] 2015-08-11 15:36
Ah yes, that will be fixed soon. =) Glad to help, and thanks for understanding again!
